version: "3.9"

services:

  # ==============================
  # Backend (Node.js API)
  # ==============================
  backend:
    build: .
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - ./src/.env
    depends_on:
      - rabbitmq
      - nlpservice
    restart: always

  # ==============================
  # RabbitMQ (Message Broker)
  # ==============================
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: strongpassword

  # ==============================
  # MongoDB UI (External DB)
  # ==============================
  mongo-express:
    image: mongo-express
    container_name: mongo-ui
    restart: always
    ports:
      - "8081:8081"
    environment:
        ME_CONFIG_MONGODB_URL: mongodb://mongo.splsystems.in:27017/
        ME_CONFIG_BASICAUTH: "false"

  # ==============================
  # NLP / AI Service
  # ==============================
  nlpservice:
    build: ./AI
    container_name: nlpservice
    ports:
      - "5000:5000"
    restart: always